name: Notify Discord

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notificar Discord em caso de falha
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"❌ Build falhou no repositório!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
